##	Writen by: Oscar Bergström
##  	https://github.com/OSCARJFB
##	
##	MIT License
##	Copyright (c) 2024 Oscar Bergström

cc = gcc
cflags = -Wall -Wextra -Werror -pedantic
crflgs = -03 -march=native -mtune=native -fito -fomit-frame-pointer

main:
	$(cc) main.c Console.c Game.c $(cflags) -o main.o
